<a href="https://colab.research.google.com/github/Bobojon-Py-Data-Scientist/Bot_telegram/blob/main/Chiziqli_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Chiziqli Algebra

In [1]:
import  numpy as np

In [3]:
x =np.array([[1., 2., 3.,], [4., 5., 6.,]])

In [13]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
y= np.array([[5., 5., 5.,], [4., 4., 4.,]])

In [14]:
y

array([[5., 5., 5.],
       [4., 4., 4.]])

In [5]:
x+y

array([[ 6.,  7.,  8.],
       [ 8.,  9., 10.]])

In [6]:
x*5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [15]:
x =np.array([[1., 2., 3.,], [4., 5., 6.,]])

In [16]:
y = np.array([[6., 23.,], [-1., 7], [8, 9]])

In [ ]:
x.dot(y)

bunda x va y qaysisini yozsak 1-nchi osha ustun boyicha yoziladi!!!

In [19]:
y.dot(x)

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

npdot (x y)  bunda x ustuni boyicha chiqaradi  javobini!!!
Buyerdayam x yoki y qaysisi 1-nchi yozilganiga qarab ustunini chiqaradi!!!

In [18]:
np.dot(x, y) 

array([[ 28.,  64.],
       [ 67., 181.]])

In [20]:
np.dot(y, x)


array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])